---
title: "Assgnment 6"
author: "Niharika Pillanagoyala"
Date: 11/19/2021
output:
  word_document: default
  html_document: default
---

# Loading libraries

```{r}

library(lpSolveAPI)
lp <- make.lp(0,12)
lp.control(lp, sense="max")
# objective function
time <- c(5, 3, 4, 2, 3, 1, 4, 6, 2, 5, 4, 7) 
set.objfn(lp, 1*time)
set.type(lp, 1:12, "binary") 
# starting node
add.constraint(lp,c(1,1),"=",1,indices = c(1,2)) 
# intermediate node
add.constraint(lp,c(1,-1,-1),"=",0,indices = c(1,3,4)) 
add.constraint(lp,c(1,-1),"=",0,indices = c(2,5))
add.constraint(lp,c(1,-1,-1),"=",0,indices = c(3,6,7))
add.constraint(lp,c(1,1,-1,-1),"=",0,indices = c(4,5,8,9))
add.constraint(lp,c(1, -1),"=",0,indices = c(6,10))
add.constraint(lp,c(1,1,-1),"=",0,indices = c(7,8,11))
add.constraint(lp,c(1,-1),"=",0,indices = c(9,12))
# End node
add.constraint(lp,c(1,1,1),"=",1,indices = c(10,11,12)) 
solve(lp)
get.objective(lp)
get.variables(lp)
get.constraints(lp)
arc <- c("x12", "x13", "x24", "x25", "x35", "x46", "x47", "x57", "x58", "x69", "x79", "x89")
variables<-get.variables(lp)
output<-data.frame(arc,variables)
output

```

# 2a)

```{r}

lps<-make.lp(0,8)
lp.control(lps,sense="max")
#As we are implementing integer programming we will set the type to integer
set.objfn(lps,c(4,6.5,5.9,5.4,5.15,10,8.4,6.25))
set.type(lps,c(1:8), type = "integer")
add.constraint(lps,c(40,50,80,60,45,60,30,25),"<=",2500000,indices = c(1:8))
add.constraint(lps,1000,">=",0,indices = 1)
add.constraint(lps,1000,">=",0,indices = 2)
add.constraint(lps,1000,">=",0,indices = 3)
add.constraint(lps,1000,">=",0,indices = 4)
add.constraint(lps,1000,">=",0,indices = 5)
add.constraint(lps,1000,">=",0,indices = 6)
add.constraint(lps,1000,">=",0,indices = 7)
add.constraint(lps,1000,">=",0,indices = 8)
add.constraint(lps,40,">=",100000,indices = 1)
add.constraint(lps,50,">=",100000,indices = 2)
add.constraint(lps,80,">=",100000,indices = 3)
add.constraint(lps,60,">=",100000,indices = 4)
add.constraint(lps,45,">=",100000,indices = 5)
add.constraint(lps,60,">=",100000,indices = 6)
add.constraint(lps,30,">=",100000,indices = 7)
add.constraint(lps,25,">=",100000,indices = 8)
add.constraint(lps,c(40,50,80),"<=",1000000,indices = c(1,2,3))
add.constraint(lps,c(60,45,60),"<=",1000000,indices = c(4,5,6))
add.constraint(lps,c(30,25),"<=",1000000,indices = c(7,8))
solve(lps)
get.objective(lps)
get.variables(lps)
get.constraints(lps)


```

# 2b)

```{r}

lps1<-make.lp(0,8)
lp.control(lps1,sense="max")
#Formulating without integer
set.objfn(lps1,c(4,6.5,5.9,5.4,5.15,10,8.4,6.25))
add.constraint(lps1,c(40,50,80,60,45,60,30,25),"<=",2500000,indices = c(1:8))
add.constraint(lps1,1000,">=",0,indices = 1)
add.constraint(lps1,1000,">=",0,indices = 2)
add.constraint(lps1,1000,">=",0,indices = 3)
add.constraint(lps1,1000,">=",0,indices = 4)
add.constraint(lps1,1000,">=",0,indices = 5)
add.constraint(lps1,1000,">=",0,indices = 6)
add.constraint(lps1,1000,">=",0,indices = 7)
add.constraint(lps1,1000,">=",0,indices = 8)
add.constraint(lps1,40,">=",100000,indices = 1)
add.constraint(lps1,50,">=",100000,indices = 2)
add.constraint(lps1,80,">=",100000,indices = 3)
add.constraint(lps1,60,">=",100000,indices = 4)
add.constraint(lps1,45,">=",100000,indices = 5)
add.constraint(lps1,60,">=",100000,indices = 6)
add.constraint(lps1,30,">=",100000,indices = 7)
add.constraint(lps1,25,">=",100000,indices = 8)
add.constraint(lps1,c(40,50,80),"<=",1000000,indices = c(1,2,3))
add.constraint(lps1,c(60,45,60),"<=",1000000,indices = c(4,5,6))
add.constraint(lps1,c(30,25),"<=",1000000,indices = c(7,8))
solve(lps1)
get.objective(lps1)
get.variables(lps1)
get.constraints(lps1)

```



